name: reviewdog
on: [pull_request]
jobs:
  # NOTE: golangci-lint doesn't report multiple errors on the same line from
  # different linters and just report one of the errors?

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Add Path
        run: |
          echo ::add-path::$(go env GOPATH)/bin # for Go projects

      - name: Install linters
        run: |
          go get golang.org/x/lint/golint

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin

      - name: Run reviewdog(golint)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -name=golint-check -reporter=github-pr-check -level=warning -diff="git diff master2"

      - name: Run reviewdog(golangci-lint)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golangci-lint run --out-format line-number --exclude-use-default=false | reviewdog -f=golangci-lint -name=golang-lint-check -reporter=github-pr-check -level=error -diff="git diff master2"

